const C = window.STUDIO_CONFIG;
const state = { token: localStorage.getItem('reinou_token') || '', user: null, data: {}, page: 'dashboard' };
const MODULES = [
  ['dashboard','工作台'],['projects','專案'],['tasks','任務'],['events','活動'],['staff','人員'],['schedule','排班'],['finance','財務'],['payroll','薪資'],['contracts','合約'],['performance','績效']
];
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money = n => new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(n||0));
const date = s => s ? new Date(s).toLocaleDateString('zh-TW') : '—';
function toast(msg,bad=false){const el=$('#toast');el.textContent=msg;el.style.cssText=`position:fixed;top:18px;left:50%;transform:translateX(-50%);z-index:999;background:${bad?'#4a1717':'#202020'};color:white;padding:11px 16px;border-radius:12px;border:1px solid #333;box-shadow:0 10px 30px #0008`;setTimeout(()=>el.textContent='',2600)}
async function api(action, payload={}){
  if(!C.API_URL || C.API_URL.includes('PASTE_')) throw new Error('請先在 config.js 填入 Apps Script Web App URL');
  const body={action,payload,token:state.token};
  const r=await fetch(C.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});
  const j=await r.json(); if(!j.ok) throw new Error(j.error||'API 錯誤'); return j.data;
}
function setAuth(on){$('#loginView').classList.toggle('hidden',on);$('#appView').classList.toggle('hidden',!on)}
async function boot(){ if(!state.token){setAuth(false);return} try{state.user=await api('me');setAuth(true);renderNav();await loadPage('dashboard')}catch(e){localStorage.removeItem('reinou_token');state.token='';setAuth(false)} }
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('login',{username:$('#loginUsername').value.trim(),password:$('#loginPassword').value});state.token=d.token;state.user=d.user;localStorage.setItem('reinou_token',state.token);setAuth(true);renderNav();await loadPage('dashboard');toast('登入成功')}catch(err){toast(err.message,true)}});
$('#logoutBtn').onclick=async()=>{try{await api('logout')}catch{} localStorage.removeItem('reinou_token');location.reload()};
$('#refreshBtn').onclick=()=>loadPage(state.page);
function renderNav(){const html=MODULES.map(([id,name])=>`<button class="nav-btn ${state.page===id?'active':''}" data-page="${id}"><span class="nav-dot"></span>${name}</button>`).join('');$('#sideNav').innerHTML=html;$('#mobileNav').innerHTML=MODULES.slice(0,5).map(([id,name])=>`<button class="nav-btn ${state.page===id?'active':''}" data-page="${id}"><span class="nav-dot"></span>${name}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>loadPage(b.dataset.page));$('#miniUser').innerHTML=`<strong>${esc(state.user?.name)}</strong><br><span class="muted">${esc(state.user?.role)}</span>`}
async function loadPage(page){state.page=page;renderNav();const names=Object.fromEntries(MODULES);$('#pageTitle').textContent=names[page]||page;$('#content').innerHTML='<div class="empty">讀取中…</div>';try{const d=await api('page',{page});state.data[page]=d;renderPage(page,d);updateNotify(d.notifications)}catch(e){$('#content').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function updateNotify(n){const c=Array.isArray(n)?n.filter(x=>String(x.read).toLowerCase()!=='true').length:0;$('#notifyBadge').textContent=c;$('#notifyBadge').classList.toggle('hidden',!c)}
function pill(v){const s=String(v||'');const cls=/完成|已付|已簽|通過|正常|已結案/.test(s)?'ok':/逾期|駁回|取消|未付/.test(s)?'bad':'warn';return `<span class="pill ${cls}">${esc(s||'—')}</span>`}
function hero(title,sub,button=''){return `<div class="hero"><div><h3>${esc(title)}</h3><p>${esc(sub)}</p></div>${button}</div>`}
function list(items, titleKey='title', metaFn=x=>''){return items?.length?`<div class="list">${items.map(x=>`<div class="list-item"><div class="list-main"><div class="list-title">${esc(x[titleKey])}</div><div class="list-meta">${metaFn(x)}</div></div>${x.status?pill(x.status):''}</div>`).join('')}</div>`:'<div class="empty">目前沒有資料</div>'}
function renderPage(page,d){const fn={dashboard:renderDashboard,projects:renderProjects,tasks:renderTasks,events:renderEvents,staff:renderStaff,schedule:renderSchedule,finance:renderFinance,payroll:renderPayroll,contracts:renderContracts,performance:renderPerformance}[page];$('#content').innerHTML=fn?fn(d):'<div class="empty">尚未完成</div>';bindActions()}
function renderDashboard(d){return `${hero(`晚安，${state.user?.name||'夥伴'}`,'這裡是今天的工作室營運摘要。')}<div class="grid cols-4"><div class="card"><div class="metric-label">進行中專案</div><div class="metric">${d.metrics?.projects||0}</div></div><div class="card"><div class="metric-label">我的待辦</div><div class="metric">${d.metrics?.tasks||0}</div></div><div class="card"><div class="metric-label">本月收入</div><div class="metric">${money(d.metrics?.income)}</div></div><div class="card"><div class="metric-label">待支付薪資</div><div class="metric">${money(d.metrics?.payroll)}</div></div></div><div class="grid cols-2" style="margin-top:16px"><div class="card"><h4>近期任務</h4>${list(d.tasks,'title',x=>`${esc(x.assigneeName||'未指派')} · ${date(x.dueDate)}`)}</div><div class="card"><h4>近期活動</h4>${list(d.events,'name',x=>`${date(x.startDate)} · ${esc(x.venue||'未定地點')}`)}</div></div>`}
function renderProjects(d){return `${hero('專案中心','管理賽事、設計、合作與所有工作室案件。','<button class="btn primary" data-new="project">＋ 新增專案</button>')}<div class="grid cols-3">${(d.items||[]).map(x=>`<div class="card"><div class="eyebrow">${esc(x.code||'PROJECT')}</div><h3 style="margin:8px 0">${esc(x.name)}</h3><div class="muted" style="font-size:12px">${esc(x.ownerName||'未指定')} · ${date(x.dueDate)}</div><div class="progress"><span style="width:${Math.max(0,Math.min(100,Number(x.progress||0)))}%"></span></div><div class="section-head" style="margin:12px 0 0"><span class="muted" style="font-size:12px">${x.progress||0}%</span>${pill(x.status)}</div></div>`).join('')||'<div class="empty">尚無專案</div>'}</div>`}
function renderTasks(d){return tablePage('任務管理','追蹤指派、審核與截止日。','task',['標題','負責人','專案','截止日','狀態'],(d.items||[]).map(x=>[x.title,x.assigneeName,x.projectName,date(x.dueDate),pill(x.status)]))}
function renderEvents(d){return tablePage('活動管理','管理比賽、直播、會議與實體活動。','event',['活動','類型','日期','地點','狀態'],(d.items||[]).map(x=>[x.name,x.type,date(x.startDate),x.venue,pill(x.status)]))}
function renderStaff(d){return tablePage('人員中心','正式成員、接案、主播與合作人才。','staff',['姓名','部門','職位','型態','狀態'],(d.items||[]).map(x=>[x.name,x.department,x.title,x.type,pill(x.status)]))}
function renderSchedule(d){return tablePage('排班中心','工作日、活動日、值班與可接案時段。','schedule',['人員','日期','班別','開始','結束'],(d.items||[]).map(x=>[x.staffName,date(x.date),x.shift,x.startTime,x.endTime]))}
function renderFinance(d){return `${hero('財務中心','掌握收入、支出與專案損益。','<button class="btn primary" data-new="finance">＋ 新增收支</button>')}<div class="grid cols-3"><div class="card"><div class="metric-label">收入</div><div class="metric">${money(d.summary?.income)}</div></div><div class="card"><div class="metric-label">支出</div><div class="metric">${money(d.summary?.expense)}</div></div><div class="card"><div class="metric-label">損益</div><div class="metric">${money((d.summary?.income||0)-(d.summary?.expense||0))}</div></div></div>${table(['日期','類型','項目','專案','金額'],(d.items||[]).map(x=>[date(x.date),x.type,x.title,x.projectName,money(x.amount)]))}`}
function renderPayroll(d){return tablePage('薪資中心','薪資、合作費、出場費與付款狀態。','payroll',['人員','月份','項目','金額','狀態'],(d.items||[]).map(x=>[x.staffName,x.month,x.item,money(x.amount),pill(x.status)]))}
function renderContracts(d){return tablePage('合約中心','合作、主播、贊助與活動文件狀態。','contract',['合約','對象','專案','到期日','狀態'],(d.items||[]).map(x=>[x.title,x.party,x.projectName,date(x.endDate),pill(x.status)]))}
function renderPerformance(d){return tablePage('績效中心','以期間記錄目標、評分與主管回饋。','performance',['人員','期間','完成任務','準時率','評分'],(d.items||[]).map(x=>[x.staffName,x.period,x.completed,x.onTimeRate?`${x.onTimeRate}%`:'—',x.score||'—']))}
function tablePage(title,sub,type,heads,rows){return `${hero(title,sub,`<button class="btn primary" data-new="${type}">＋ 新增</button>`)}${table(heads,rows)}`}
function table(heads,rows){return `<div class="table-wrap"><table class="table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c??'—'}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${heads.length}" class="muted">目前沒有資料</td></tr>`}</tbody></table></div>`}
function bindActions(){document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>openCreate(b.dataset.new))}
const FIELDS={
 project:[['name','專案名稱'],['code','專案代碼'],['ownerName','負責人'],['dueDate','截止日期','date'],['status','狀態'],['progress','進度 %','number'],['budget','預算','number'],['description','說明','textarea']],
 task:[['title','任務標題'],['projectName','專案'],['assigneeName','負責人'],['dueDate','截止日期','date'],['status','狀態'],['priority','優先級'],['description','工作內容','textarea']],
 event:[['name','活動名稱'],['type','類型'],['startDate','開始日期','date'],['endDate','結束日期','date'],['venue','地點'],['ownerName','負責人'],['status','狀態'],['description','說明','textarea']],
 staff:[['name','姓名'],['username','登入帳號'],['department','部門'],['title','職位'],['type','人員型態'],['role','系統角色'],['status','狀態'],['baseSalary','基本薪資','number']],
 schedule:[['staffName','人員'],['date','日期','date'],['shift','班別'],['startTime','開始時間','time'],['endTime','結束時間','time'],['note','備註']],
 finance:[['date','日期','date'],['type','類型（收入/支出）'],['title','項目'],['projectName','專案'],['amount','金額','number'],['method','付款方式'],['note','備註']],
 payroll:[['staffName','人員'],['month','月份'],['item','項目'],['amount','金額','number'],['status','狀態'],['payDate','付款日','date']],
 contract:[['title','合約名稱'],['party','合作對象'],['projectName','專案'],['startDate','開始日','date'],['endDate','到期日','date'],['amount','金額','number'],['status','狀態'],['fileUrl','檔案網址']],
 performance:[['staffName','人員'],['period','期間'],['completed','完成任務','number'],['onTimeRate','準時率 %','number'],['score','評分','number'],['comment','主管回饋','textarea']]
};
function openCreate(type){const fields=FIELDS[type];if(!fields)return;$('#modalContent').innerHTML=`<h2 style="margin-top:0">新增${type}</h2><div class="form-grid">${fields.map(([k,l,t='text'])=>`<label class="${t==='textarea'?'full-span':''}">${l}${t==='textarea'?`<textarea name="${k}"></textarea>`:`<input name="${k}" type="${t}">`}</label>`).join('')}</div><div class="actions" style="margin-top:18px"><button type="button" class="btn primary" id="saveModal">儲存</button></div>`;$('#modal').showModal();$('#saveModal').onclick=async()=>{const obj={};$('#modalContent').querySelectorAll('[name]').forEach(i=>obj[i.name]=i.type==='number'?Number(i.value||0):i.value.trim());try{await api('create',{type,data:obj});$('#modal').close();toast('已建立');loadPage(state.page)}catch(e){toast(e.message,true)}}}
boot();
